name: chopper_example
description: Example of Chopper
version: 0.0.1
#homepage: https://www.example.com
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  meta:
  chopper: ^1.0.0
  jaguar_serializer: ^2.0.0

dev_dependencies:
  build_runner: ^0.9.0
  chopper_generator: ^1.0.0
  jaguar_serializer_cli: ^2.0.0

dependency_overrides:
  chopper:
    path: ../chopper
  chopper_generator:
    path: ../chopper_generator
