name: chopper_example
description: Example of Chopper
version: 0.0.1
#homepage: https://www.example.com
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  angular: ^5.0.0
  meta:
  chopper: ^1.0.0
  jaguar_serializer: ^2.0.0
  json_annotation: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  chopper_generator: ^1.2.0-dev1
  jaguar_serializer_cli: ^2.0.0
  build_web_compilers: ^0.4.0+4
  json_serializable: ^1.3.0

dependency_overrides:
  chopper:
    path: ../chopper
  chopper_generator:
    path: ../chopper_generator
