name: swagger_chopper
description: Generate a chopper definition from swagger
version: 0.0.1
homepage: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.2
  analyzer: ^0.33.0
  build: ^1.0.0
  logging: ^0.11.0
  code_builder: ^3.0.0
  built_collection: ^3.1.3
  built_value: ^6.3.0
  build_config: ^0.3.0
  swagger_built_value:
    path: ../swagger_built_value

dev_dependencies:
  build_runner:
  built_value_generator:
  test: ^1.3.0

dependency_overrides:
  chopper:
    path: ../chopper
  chopper_generator:
    path: ../chopper_generator
  swagger_built_value:
    path: ../swagger_built_value