name: chopper_built_value
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 0.0.1
homepage: https://hadrien-lejard.gitbook.io/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  built_value: ^6.7.1
  built_collection: ^4.2.2
  chopper: ^3.0.0
  http: ^0.12.0

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.0.0
  build_test:
  coverage: ^0.12.2
  test_coverage: ^0.3.0
  built_value_generator: ^6.0.0
  pedantic: ^1.0.0