name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Chopper
      env:
        PKG: chopper
      run: bash ./tool/travis.sh dartanalyzer dartfmt test
      
    - name: Chopper Generator
      env:
        PKG: chopper_generator
      run: bash ./tool/travis.sh dartanalyzer dartfmt test
      
    - name: Chopper Built Value
      env:
        PKG: chopper_built_value
      run: bash ./tool/travis.sh dartanalyzer dartfmt test
